server:
  port: 80

spring:
  application:
    name: cloud-consumer-order


eureka:
  client:
    #表示将自己注册进入eureka-server默认为true
    register-with-eureka: true
    #是否从eureka-server抓取已有注册信息，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

  instance:
      instance-id: order80 #服务名称
      prefer-ip-address: true #显示ip
      #eureka客户端向服务端发送心跳检测时间间隔，默认30s
      lease-renewal-interval-in-seconds: 1
      #eureka服务端收到最后一次心跳检测后等待时间上限，默认90s，超时就会删除服务
      lease-expiration-duration-in-seconds: 2